workflows:
  flutter_build_with_secrets:
    name: Flutter Android Build with Secrets
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      groups:
        - keystore_credentials
      vars:
        PACKAGE_NAME: "com.user_borrow_app"
        GOOGLE_PLAY_TRACK: "alpha"

    scripts:
      - name: Set up Flutter SDK path
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Generate secrets.dart from environment variable
        script: |
          echo "$SECRETS_FILE" > lib/secrets.dart
          echo "✅ secrets.dart created successfully"
          ls -l lib/secrets.dart

      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
